language: go
go:
- '1.6.3'
- 'tip'
env:
  global:
    - GOARCH=amd64
script:
  ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
matrix:
  allow_failures:
    - go: tip
